[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.unit-tests]
command = "cargo"
args = ["test"]

[tasks.build-google]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-google"]

[tasks.build-google-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-google", "--no-default-features"]

[tasks.build-brave]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-brave"]

[tasks.build-brave-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-brave", "--no-default-features"]

[tasks.build-tavily]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-tavily"]

[tasks.build-tavily-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-tavily", "--no-default-features"]

[tasks.build-serper]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-serper"]

[tasks.build-serper-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-serper", "--no-default-features"]

[tasks.build]
dependencies = [
    "build-google",
    "build-brave",
    "build-tavily",
    "build-serper",
]

[tasks.build-portable]
dependencies = [
    "build-google-portable",
    "build-brave-portable",
    "build-tavily-portable",
    "build-serper-portable",
]

[tasks.build-all]
script_runner = "@duckscript"
script = '''
mkdir ../components/web-search/debug

cm_run_task clean
cm_run_task build

cp ../target/wasm32-wasip1/debug/golem_websearch_google.wasm ../components/web-search/debug/golem_websearch_google.wasm
cp ../target/wasm32-wasip1/debug/golem_websearch_brave.wasm ../components/web-search/debug/golem_websearch_brave.wasm
cp ../target/wasm32-wasip1/debug/golem_websearch_tavily.wasm ../components/web-search/debug/golem_websearch_tavily.wasm
cp ../target/wasm32-wasip1/debug/golem_websearch_serper.wasm ../components/web-search/debug/golem_websearch_serper.wasm

cm_run_task clean
cm_run_task build-portable

cp ../target/wasm32-wasip1/debug/golem_websearch_google.wasm ../components/web-search/debug/golem_websearch_google-portable.wasm
cp ../target/wasm32-wasip1/debug/golem_websearch_brave.wasm ../components/web-search/debug/golem_websearch_brave-portable.wasm
cp ../target/wasm32-wasip1/debug/golem_websearch_tavily.wasm ../components/web-search/debug/golem_websearch_tavily-portable.wasm
cp ../target/wasm32-wasip1/debug/golem_websearch_serper.wasm ../components/web-search/debug/golem_websearch_serper-portable.wasm
'''

[tasks.release-build-google]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-google", "--release"]

[tasks.release-build-google-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-google", "--release", "--no-default-features"]

[tasks.release-build-brave]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-brave", "--release"]

[tasks.release-build-brave-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-brave", "--release", "--no-default-features"]

[tasks.release-build-tavily]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-tavily", "--release"]

[tasks.release-build-tavily-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-tavily", "--release", "--no-default-features"]

[tasks.release-build-serper]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-serper", "--release"]

[tasks.release-build-serper-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-websearch-serper", "--release", "--no-default-features"]

[tasks.release-build]
dependencies = [
    "release-build-google",
    "release-build-brave",
    "release-build-tavily",
    "release-build-serper",
]

[tasks.release-build-portable]
dependencies = [
    "release-build-google-portable",
    "release-build-brave-portable",
    "release-build-tavily-portable",
    "release-build-serper-portable",
]

[tasks.release-build-all]
script_runner = "@duckscript"
script = '''
mkdir ../components/web-search/release

cm_run_task set-version

cm_run_task clean
cm_run_task release-build

cp ../target/wasm32-wasip1/release/golem_websearch_google.wasm ../components/web-search/release/golem_websearch_google.wasm
cp ../target/wasm32-wasip1/release/golem_websearch_brave.wasm ../components/web-search/release/golem_websearch_brave.wasm
cp ../target/wasm32-wasip1/release/golem_websearch_tavily.wasm ../components/web-search/release/golem_websearch_tavily.wasm
cp ../target/wasm32-wasip1/release/golem_websearch_serper.wasm ../components/web-search/release/golem_websearch_serper.wasm

cm_run_task clean
cm_run_task release-build-portable

cp ../target/wasm32-wasip1/release/golem_websearch_google.wasm ../components/web-search/release/golem_websearch_google-portable.wasm
cp ../target/wasm32-wasip1/release/golem_websearch_brave.wasm ../components/web-search/release/golem_websearch_brave-portable.wasm
cp ../target/wasm32-wasip1/release/golem_websearch_tavily.wasm ../components/web-search/release/golem_websearch_tavily-portable.wasm
cp ../target/wasm32-wasip1/release/golem_websearch_serper.wasm ../components/web-search/release/golem_websearch_serper-portable.wasm
'''

[tasks.wit-update]
install_crate = { crate_name = "wit-deps-cli" }
command = "wit-deps"
args = ["update"]

[tasks.wit]
dependencies = ["wit-update"]
script_runner = "@duckscript"
script = """
rm -r web-search/wit/deps
mkdir web-search/wit/deps/golem-web-search
cp wit/golem-web-search.wit web-search/wit/deps/golem-web-search/golem-web-search.wit
cp wit/deps/wasi:io web-search/wit/deps

rm -r websearch-google/wit/deps
mkdir websearch-google/wit/deps/golem-web-search
cp wit/golem-web-search.wit websearch-google/wit/deps/golem-web-search/golem-web-search.wit
cp wit/deps/wasi:io websearch-google/wit/deps

rm -r websearch-brave/wit/deps
mkdir websearch-brave/wit/deps/golem-web-search
cp wit/golem-web-search.wit websearch-brave/wit/deps/golem-web-search/golem-web-search.wit
cp wit/deps/wasi:io websearch-brave/wit/deps

rm -r websearch-tavily/wit/deps
mkdir websearch-tavily/wit/deps/golem-web-search
cp wit/golem-web-search.wit websearch-tavily/wit/deps/golem-web-search/golem-web-search.wit
cp wit/deps/wasi:io websearch-tavily/wit/deps

rm -r websearch-serper/wit/deps
mkdir websearch-serper/wit/deps/golem-web-search
cp wit/golem-web-search.wit websearch-serper/wit/deps/golem-web-search/golem-web-search.wit
cp wit/deps/wasi:io websearch-serper/wit/deps
"""

[tasks.check]
description = "Runs rustfmt and clippy checks without applying any fix"
dependencies = ["check-clippy", "check-rustfmt"]

[tasks.check-rustfmt]
description = "Runs rustfmt checks without applying any fix"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check-clippy]
description = "Runs clippy checks without applying any fix"
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--", "--no-deps", "-Dwarnings"]

[tasks.fix]
description = "Runs rustfmt and clippy checks and applies fixes"
dependencies = ["wit", "fix-clippy", "fix-rustfmt"]

[tasks.fix-rustfmt]
description = "Runs rustfmt checks and applies fixes"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fix-clippy]
description = "Runs clippy checks and applies fixes"
install_crate = "clippy"
command = "cargo"
args = [
    "clippy",
    "--fix",
    "--allow-dirty",
    "--allow-staged",
    "--",
    "--no-deps",
    "-Dwarnings",
]


# cargo-binstall golem-cli@1.2.2-dev.11 --locked --force --no-confirm
# cargo-binstall wac-cli --locked --force --no-confirm

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds all test components with golem-cli"
install_crate = "cargo-binstall"
script = '''
cd test
golem-cli --version
golem-cli app clean
golem-cli app build -b google-debug
golem-cli app clean
golem-cli app build -b brave-debug
golem-cli app clean
golem-cli app build -b tavily-debug
golem-cli app clean
golem-cli app build -b serper-debug
'''


[tasks.set-version]
description = "Sets the version in all Cargo.toml files to the value of the VERSION environment variable"
condition = { env_set = ["VERSION"] }
script = '''
grep -rl --include 'Cargo.toml' '0\.0\.0' | xargs sed -i "s/0\.0\.0/${VERSION}/g"
'''

[tasks.set-version.mac]
condition = { env_set = ["VERSION"] }
script = '''
grep -rl --include '.*Cargo\.toml' '0\.0\.0' | xargs sed -i "" "s/0\.0\.0/${VERSION}/g"
'''

[tasks.set-version.windows]
script_runner = "powershell"
script_extension = "ps1"
condition = { env_set = ["VERSION"] }
script = '''
$cargoFiles = Get-ChildItem . Cargo.toml -rec
foreach ($file in $cargoFiles)
{
    (Get-Content $file.PSPath) |
    Foreach-Object { $_ -replace "0.0.0", $Env:VERSION } |
    Set-Content $file.PSPath
}
'''